### PR TITLE
make text box draggable

### PR DESCRIPTION
**Pull request by shushengfuqin**
### Summary 
make the basic draggable for the text box in the editor

### Details
draggable text box

### How to test?
In the editor try to draggle the text box.
Add some text save it
return to the workbench page and edit the saved experience and see if the text is still saved

### Checks 
- [ ] Tested Changes
- [ ] Stakeholder Approval

### CODE REVIEW

**Review by Ysabz — APPROVED** [review]
Works well. great job. The text box in Preview mode could also be draggable . Another enhancement could be to make the text box resizable.

**Comment by shushengfuqin** [comment]
> Works well. great job. The text box in Preview mode could also be draggable . Another enhancement could be to make the text box resizable.

done for the preview mode text box. Have to do more tests for the resize issue.

**Comment by shushengfuqin** [comment]
> Works well. great job. The text box in Preview mode could also be draggable . Another enhancement could be to make the text box resizable.

Also I think that for resize, it will be more about the editor version instead of the preview version?

**Comment by shushengfuqin** [comment]
> > > Works well. great job. The text box in Preview mode could also be draggable . Another enhancement could be to make the text box resizable.
> > 
> > 
> > Also I think that for resize, it will be more about the editor version instead of the preview version?
> 
> I think it is useful for both. The reason I suggested this is to enable users to show more lines of text ( currently it's limited to two rows)

the editor version is fixed. looking at the presentation version

**Comment by mckenzietsean** [comment]
> > > > Works well. great job. The text box in Preview mode could also be draggable . Another enhancement could be to make the text box resizable.
> > > 
> > > 
> > > Also I think that for resize, it will be more about the editor version instead of the preview version?
> > 
> > 
> > I think it is useful for both. The reason I suggested this is to enable users to show more lines of text ( currently it's limited to two rows)
> 
> the editor version is fixed. looking at the presentation version

I can confirm that this is both fixed and fully functional. I was originally going to comment about how the lines of text were buggy like pic below but that issue is resolved and the user can show more lines of text without the textbox breaking.
unknown
.

**Review by mckenzietsean — APPROVED** [review]

**Comment by shushengfuqin** [comment]
> > > > > Works well. great job. The text box in Preview mode could also be draggable . Another enhancement could be to make the text box resizable.
> > > > 
> > > > 
> > > > Also I think that for resize, it will be more about the editor version instead of the preview version?
> > > 
> > > 
> > > I think it is useful for both. The reason I suggested this is to enable users to show more lines of text ( currently it's limited to two rows)
> > 
> > 
> > the editor version is fixed. looking at the presentation version
> 
> I can confirm that this is both fixed and fully functional. I was originally going to comment about how the lines of text were buggy like pic below but that issue is resolved and the user can show more lines of text without the textbox breaking. unknown .

should be solved

**Pull request merged**
