### PR TITLE
Font refactor

### PR DESCRIPTION
**Pull request by Ysabz**
### Summary 
This PR enhances the font family and size througout different pages
### Details
_provide the updates in bullet points_
### How to test?
test as before
### Checks 
- [ ] Tested Changes
- [ ] Stakeholder Approval

### CODE REVIEW

**Review by tashfia98 — APPROVED** [review]
Looks great! Nice work.

**Review by shushengfuqin — APPROVED** [review]
Function looks good. The only thing that we might have to fix for the next pr are the modified time in the workbench and then the appratus list. Feels like half of it are empty. maybe we can remove these part by making the appratus list box slimer
Screen Shot 2022-03-28 at 20 59 17
Screen Shot 2022-03-28 at 20 58 54

**Review by JustinLohKingWei — APPROVED** [review]
Testing was carried out according to specified procedures and there was no errors or unexpected behavior. Therefore I am approving this PR

**Review by mckenzietsean — APPROVED** [review]
Looks good to me.

**Pull request merged**
