### PR TITLE
Static web UI fix

### PR DESCRIPTION
**Pull request by Ysabz**
### Summary 
This PR fixes the icon button color bug in static website 

### How to test?
Test as before
### Checks 
- [ ] Tested Changes
- [ ] Stakeholder Approval

### CODE REVIEW

**Comment by shushengfuqin** [comment]
But the color for the icons on the side bar are perfect.

**Review by shushengfuqin — APPROVED** [review]
The rest lgtm

**Review by tashfia98 — APPROVED** [review]
The static web issues seems to be fixed, great work! However, i noticed this on workbench page. "Do you wish to logout" seems a bit less visible. 
image

**Comment by Ysabz** [comment]
> The static web issues seems to be fixed, great work! However, i noticed this on workbench page. "Do you wish to logout" seems a bit less visible. image

Yes I have noticed that as well. same thing in the login page. Will try to fix it

**Pull request merged**
