### PR TITLE
Login Page Tests

### PR DESCRIPTION
**Pull request by mckenzietsean**
### Summary 
New tests for the Login page. Also fixed a bug with tests crashing because of a lack of router instances.
### Details
- Added 4 new tests for login
- Fixed issue with index and login tests crashing from having no router instance
- There are still 2 tests that fail (PreviewOverlay.test.tsx)
### How to test?
1. Open project
2. Run tests using "yarn test"
3. login.test.tsx should pass
4. index.test.tsx should also be passing now

### CODE REVIEW

**Comment by shushengfuqin** [comment]
Seems that there are some duplicate codes in the login.test.tsx. Mind double-check, and see how to remove them?

**Comment by shushengfuqin** [comment]
In each of your test, they are having similar lines right, so how about we make them global, or we can define them in a beforeEach or beforeAll
you can look at the setup and teardown for test in this part
https://jestjs.io/docs/setup-teardown

**Comment by shushengfuqin** [comment]
lgtm
@yasaman1377 
@Ysabz @JustinLohKingWei @tashfia98 
please take a look when you guys have time to make sure that we didn't miss any functionalities. 
Thx

**Review by JustinLohKingWei — COMMENTED** [review]
As expected, login test and index tests are passing. Before I give my thumbs up , I assume that Preview.test is not in scope with this PR and therefore is not expected to pass?

**Comment by mckenzietsean** [comment]
>  
> 
> As expected, login test and index tests are passing. Before I give my thumbs up , I assume that Preview.test is not in scope with this PR and therefore is not expected to pass?

Correct. The PR was originally only made for login.test, but one of the fixes I had to do also fixed a problem in index.test.

**Review by JustinLohKingWei — APPROVED** [review]
As testing was carried out successfully with no unexpected results, I am approving this PR

**Pull request merged**
