### PR TITLE
Added new unity build folders + connected react buttons to unity

### PR DESCRIPTION
**Pull request by Ysabz**
This PR : 

adds the updated unity build folder ( no buttons in unity scene + assetbundles loading)
connects the react buttons to unity so the apparatus can be loaded and the triggers can be called on the apparatus

To test : 

Run the app, click on wobble sphere or earth button on the apparatus list. They should properly load. For the wobble sphere, try the triggers (still, wobble, bounce)

### CODE REVIEW

**Review by tashfia98 — COMMENTED** [review]
Webgl/Unity component not loading for me not sure why.
image

getting these 3 errors. 
image

**Comment by shushengfuqin** [comment]
tested. not working. not showing the unity WebGL.
Screen Shot 2021-11-05 at 10 15 21 PM

**Comment by Ysabz** [comment]
@shushengfuqin , @tsantalis , the issue was due to the new build files not being tracked by git. I updated the gitignore and pushed the new build files. the issue should be fixed now

**Comment by shushengfuqin** [comment]
@Ysabz  tested. it's fine. 
can be merged according to me

**Review by shushengfuqin — APPROVED** [review]

**Pull request merged**
