### PR TITLE
Parsing

### PR DESCRIPTION
**Pull request by Ysabz**
### Summary 
This PR implements the tree parsing of the apparatus json and it's integration in the apparatus list and action list
### Details
-implements the tree parsing of the json to represent the nested structure of the apparatus and the properties of each node ( identifier, type , input values , etc) 
- used the new parsing method to find the assetbundle nodes of the appratus and to show the button for each assetbundle in the apparatus list
- used the new parsing method to find the actions of each assetbundle and to show them as button in the action list
### How to test?
- run the project ( make sure the correct json files are uploaded to cloud first)
- select an appratus from appratus selection menu
- you should see all the components of the apparartus ( nested assetbundles) in the appratus box 
- after selecting each appartus you should see the actions it supports in the action list
- you should be able to add or remove actions from action sequence box
### Checks 
- [ X] Tested Changes
- [ ] Stakeholder Approval

### CODE REVIEW

**Comment by JustinLohKingWei** [comment]
The parsing function does not work and only the dummy button "SOME ASSET" is being displayed. But I understand that the previous pull request is to be merged first?

**Comment by shushengfuqin** [comment]
tested, however, it's not working. When i chose apparatus from menu, 
regadless the one i chose, I see this message.
Screen Shot 2021-11-22 at 20 18 46

Is it because the correct apparatus json is not uploaded yet? 
It's not due to CORS. thus the only reason is the fact that json is not in azure.

**Comment by Ysabz** [comment]
@JustinLohKingWei , @shushengfuqin , as mentioned in the testing steps, you need to make sure correct json files are uploaded to cloud before running. the parsing assumes a certain structure for the json files, otherwise it does not work

**Comment by shushengfuqin** [comment]
> @JustinLohKingWei , @shushengfuqin , as mentioned in the testing steps, you need to make sure correct json files are uploaded to cloud before running. the parsing assumes a certain structure for the json files, otherwise it does not work

I swapped the json files. yet i get the same result.

**Review by shushengfuqin — APPROVED** [review]
Tested the functionalities. works fine for me. The apparatus are loading without problems

**Comment by shushengfuqin** [comment]
However, seems that there are some merge conflicts that have to be solved.

**Pull request merged**
