### PR TITLE
WIndow Name Change

### PR DESCRIPTION
**Pull request by JustinLohKingWei**
### Summary 
Simple change of window name to Epista
### Details
Simple change of window name to Epista
### How to test?
1. Spin up the app and make sure it says EPISTA on the window name
### Checks 
- [X ] Tested Changes
- [ X] Stakeholder Approval

### CODE REVIEW

**Comment by shushengfuqin** [comment]
didn't look at it but approve

**Review by shushengfuqin — APPROVED** [review]
the change looks good changing to epista

**Review by tashfia98 — APPROVED** [review]
Approved

**Comment by JustinLohKingWei** [comment]
> the change looks good changing to epista

Thank you sir

**Pull request merged**
